  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 3 15 * *' # once every per month on the 15th at 03:00 UTC
      
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: go test -v ./... -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      if: matrix.platform == 'ubuntu-latest'
      uses: jandelgado/gcov2lcov-action@v1
    - name: Coveralls
      if: matrix.platform == 'ubuntu-latest'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
